name: Issues event data
on: 
  issues: 
    types: [opened, editied, closed]
  workflow_dispatch:
jobs: 
  ReportEvent:
    runs-on: ubuntu-latest
    steps:
      - name: Output Data
        run: echo "${{toJSON(github.event)}}"